apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-pods-nodes-binding
subjects:
- kind: User
  name: Jenkins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view-pods-nodes
  apiGroup: rbac.authorization.k8s.io